/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRecipeRecipeIdRouteImport } from './routes/_authenticated/recipe/$recipeId'
import { Route as AuthenticatedRecipeBookRecipeBookRouteImport } from './routes/_authenticated/recipe-book/$recipe-book'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRecipeRecipeIdRoute =
  AuthenticatedRecipeRecipeIdRouteImport.update({
    id: '/recipe/$recipeId',
    path: '/recipe/$recipeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipeBookRecipeBookRoute =
  AuthenticatedRecipeBookRecipeBookRouteImport.update({
    id: '/recipe-book/$recipe-book',
    path: '/recipe-book/$recipe-book',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/recipe-book/$recipe-book': typeof AuthenticatedRecipeBookRecipeBookRoute
  '/recipe/$recipeId': typeof AuthenticatedRecipeRecipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/recipe-book/$recipe-book': typeof AuthenticatedRecipeBookRecipeBookRoute
  '/recipe/$recipeId': typeof AuthenticatedRecipeRecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/recipe-book/$recipe-book': typeof AuthenticatedRecipeBookRecipeBookRoute
  '/_authenticated/recipe/$recipeId': typeof AuthenticatedRecipeRecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/recipe-book/$recipe-book'
    | '/recipe/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/recipe-book/$recipe-book' | '/recipe/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/recipe-book/$recipe-book'
    | '/_authenticated/recipe/$recipeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipe/$recipeId': {
      id: '/_authenticated/recipe/$recipeId'
      path: '/recipe/$recipeId'
      fullPath: '/recipe/$recipeId'
      preLoaderRoute: typeof AuthenticatedRecipeRecipeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipe-book/$recipe-book': {
      id: '/_authenticated/recipe-book/$recipe-book'
      path: '/recipe-book/$recipe-book'
      fullPath: '/recipe-book/$recipe-book'
      preLoaderRoute: typeof AuthenticatedRecipeBookRecipeBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRecipeBookRecipeBookRoute: typeof AuthenticatedRecipeBookRecipeBookRoute
  AuthenticatedRecipeRecipeIdRoute: typeof AuthenticatedRecipeRecipeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRecipeBookRecipeBookRoute:
    AuthenticatedRecipeBookRecipeBookRoute,
  AuthenticatedRecipeRecipeIdRoute: AuthenticatedRecipeRecipeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
